<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Contracts\" />
    <Folder Include="Constants\" />
    <Folder Include="Entities\Departments\" />
    <Folder Include="Entities\Employees\" />
    <Folder Include="Entities\Extinguishers\" />
    <Folder Include="Entities\Inspections\" />
    <Folder Include="Entities\Rooms\" />
    <Folder Include="Entities\Requirements\" />
    <Folder Include="Enums\" />
  </ItemGroup>

</Project>
